"""initial schema

Revision ID: 0df9a698fae1
Revises: 
Create Date: 2026-09-28 16:17:20.643157
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0df9a698fae1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.Enum('PRICE', 'FUNDAMENTAL', 'NEWS', 'SHARIAH', name='sourcekind', native_enum=False, length=16), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('frequency', sa.String(length=32), nullable=False),
    sa.Column('delay_minutes', sa.Integer(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('sectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['sectors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('failed_logins', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('exchanges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('open_time', sa.String(length=5), nullable=True),
    sa.Column('close_time', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_exchanges_market_id'), 'exchanges', ['market_id'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_user_id'), 'portfolios', ['user_id'], unique=False)
    op.create_table('shariah_methodologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('thresholds', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('prohibited_activities', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('denominator', sa.String(length=32), nullable=False),
    sa.Column('max_data_age_days', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rules', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('weights', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('level_method', sa.String(length=24), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategies_user_id'), 'strategies', ['user_id'], unique=False)
    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name')
    )
    op.create_index(op.f('ix_watchlists_user_id'), 'watchlists', ['user_id'], unique=False)
    op.create_table('backtests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('universe', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('start', sa.Date(), nullable=False),
    sa.Column('end', sa.Date(), nullable=False),
    sa.Column('costs_bps', sa.Float(), nullable=False),
    sa.Column('slippage_bps', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('trades', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtests_user_id'), 'backtests', ['user_id'], unique=False)
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=24), nullable=False),
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('activity_tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('listed_at', sa.Date(), nullable=True),
    sa.Column('delisted_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'exchange_id', name='uq_stock_ticker_exchange')
    )
    op.create_index(op.f('ix_stocks_exchange_id'), 'stocks', ['exchange_id'], unique=False)
    op.create_index(op.f('ix_stocks_isin'), 'stocks', ['isin'], unique=False)
    op.create_index(op.f('ix_stocks_sector_id'), 'stocks', ['sector_id'], unique=False)
    op.create_index(op.f('ix_stocks_ticker'), 'stocks', ['ticker'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('condition', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('channels', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_is_active'), 'alerts', ['is_active'], unique=False)
    op.create_index(op.f('ix_alerts_stock_id'), 'alerts', ['stock_id'], unique=False)
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_table('fundamentals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('period_type', sa.String(length=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('net_income', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('eps', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('total_debt', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('interest_bearing_debt', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('cash', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('interest_bearing_securities', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('receivables', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('total_assets', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('total_equity', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('interest_income', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('non_permissible_income', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('shares_outstanding', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('dividend_per_share', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('is_estimate', sa.Boolean(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'period_end', 'period_type', 'source_id')
    )
    op.create_index(op.f('ix_fundamentals_stock_id'), 'fundamentals', ['stock_id'], unique=False)
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_published_at'), 'news', ['published_at'], unique=False)
    op.create_index(op.f('ix_news_stock_id'), 'news', ['stock_id'], unique=False)
    op.create_table('portfolio_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('avg_entry', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('stop', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('target', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('opened_at', sa.Date(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_positions_portfolio_id'), 'portfolio_positions', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_portfolio_positions_stock_id'), 'portfolio_positions', ['stock_id'], unique=False)
    op.create_table('price_history',
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('interval', sa.String(length=4), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('adj_close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stock_id', 'interval', 'ts')
    )
    op.create_index('ix_price_stock_interval_ts_desc', 'price_history', ['stock_id', 'interval', sa.text('ts DESC')], unique=False)
    op.create_table('technical_indicators',
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('interval', sa.String(length=4), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stock_id', 'interval', 'ts', 'name')
    )
    op.create_table('watchlist_stocks',
    sa.Column('watchlist_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('watchlist_id', 'stock_id')
    )
    op.create_table('alert_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('delivered', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_events_alert_id'), 'alert_events', ['alert_id'], unique=False)
    op.create_table('shariah_screens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('methodology_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('COMPLIANT', 'NON_COMPLIANT', 'QUESTIONABLE', 'INSUFFICIENT_DATA', 'UNDER_REVIEW', name='shariahstatus', native_enum=False, length=24), nullable=False),
    sa.Column('business_result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ratio_results', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('fundamentals_id', sa.Integer(), nullable=True),
    sa.Column('data_as_of', sa.Date(), nullable=True),
    sa.Column('reviewer_note', sa.Text(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fundamentals_id'], ['fundamentals.id'], ),
    sa.ForeignKeyConstraint(['methodology_id'], ['shariah_methodologies.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shariah_screens_methodology_id'), 'shariah_screens', ['methodology_id'], unique=False)
    op.create_index(op.f('ix_shariah_screens_stock_id'), 'shariah_screens', ['stock_id'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('interval', sa.String(length=4), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signal_type', sa.Enum('BUY_SETUP', 'SELL_EXIT', 'HOLD', 'WAIT', 'AVOID', 'WATCHLIST', name='signaltype', native_enum=False, length=16), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('coverage', sa.Float(), nullable=True),
    sa.Column('score_breakdown', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('reasons', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('warnings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('entry_low', sa.Float(), nullable=True),
    sa.Column('entry_high', sa.Float(), nullable=True),
    sa.Column('stop', sa.Float(), nullable=True),
    sa.Column('target1', sa.Float(), nullable=True),
    sa.Column('target2', sa.Float(), nullable=True),
    sa.Column('target3', sa.Float(), nullable=True),
    sa.Column('risk_reward', sa.Float(), nullable=True),
    sa.Column('shariah_screen_id', sa.Integer(), nullable=True),
    sa.Column('data_as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shariah_screen_id'], ['shariah_screens.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_score'), 'signals', ['score'], unique=False)
    op.create_index(op.f('ix_signals_signal_type'), 'signals', ['signal_type'], unique=False)
    op.create_index(op.f('ix_signals_stock_id'), 'signals', ['stock_id'], unique=False)
    op.create_index(op.f('ix_signals_ts'), 'signals', ['ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signals_ts'), table_name='signals')
    op.drop_index(op.f('ix_signals_stock_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_signal_type'), table_name='signals')
    op.drop_index(op.f('ix_signals_score'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_shariah_screens_stock_id'), table_name='shariah_screens')
    op.drop_index(op.f('ix_shariah_screens_methodology_id'), table_name='shariah_screens')
    op.drop_table('shariah_screens')
    op.drop_index(op.f('ix_alert_events_alert_id'), table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_table('watchlist_stocks')
    op.drop_table('technical_indicators')
    op.drop_index('ix_price_stock_interval_ts_desc', table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_portfolio_positions_stock_id'), table_name='portfolio_positions')
    op.drop_index(op.f('ix_portfolio_positions_portfolio_id'), table_name='portfolio_positions')
    op.drop_table('portfolio_positions')
    op.drop_index(op.f('ix_news_stock_id'), table_name='news')
    op.drop_index(op.f('ix_news_published_at'), table_name='news')
    op.drop_table('news')
    op.drop_index(op.f('ix_fundamentals_stock_id'), table_name='fundamentals')
    op.drop_table('fundamentals')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_stock_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_is_active'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_stocks_ticker'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_sector_id'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_isin'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_exchange_id'), table_name='stocks')
    op.drop_table('stocks')
    op.drop_index(op.f('ix_backtests_user_id'), table_name='backtests')
    op.drop_table('backtests')
    op.drop_index(op.f('ix_watchlists_user_id'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_strategies_user_id'), table_name='strategies')
    op.drop_table('strategies')
    op.drop_table('shariah_methodologies')
    op.drop_index(op.f('ix_portfolios_user_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_exchanges_market_id'), table_name='exchanges')
    op.drop_table('exchanges')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('sectors')
    op.drop_table('markets')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
