"""phase 2 provider usage and symbols

Revision ID: 2e97f2e73444
Revises: 0df9a698fae1
Create Date: 2026-09-28 16:44:22.103692
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '2e97f2e73444'
down_revision = '0df9a698fae1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_usage',
    sa.Column('source_code', sa.String(length=32), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('calls', sa.Integer(), nullable=False),
    sa.Column('last_endpoint', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('source_code', 'day')
    )
    op.add_column('stocks', sa.Column('instrument_type', sa.String(length=24), nullable=False, server_default='stock'))
    op.add_column('stocks', sa.Column('provider_symbols', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'provider_symbols')
    op.drop_column('stocks', 'instrument_type')
    op.drop_table('provider_usage')
    # ### end Alembic commands ###
