"""stock fetch cooldown

Revision ID: e492b1269c24
Revises: 2e97f2e73444
Create Date: 2026-09-28 16:51:01.842985
"""
from alembic import op
import sqlalchemy as sa


revision = 'e492b1269c24'
down_revision = '2e97f2e73444'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('last_fetch_attempt_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'last_fetch_attempt_at')
    # ### end Alembic commands ###
